FROM atlassian/bitbucket-server:6.7
EXPOSE 7990
EXPOSE 7999
ENV ELASTICSEARCH_ENABLED false

ENV JVM_MINIMUM_MEMORY 1g
ENV JVM_MAXIMUM_MEMORY 1g

COPY bitbucket.properties /var/atlassian/application-data/bitbucket/shared/
